name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
jobs:
  Building_Frontend-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: React Build
        run: |
          cd frontend
          npm install
          npm run build
          
  Building_Docker_Image:
    runs-on: ubuntu-latest
    needs: Building_Frontend-Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Building Image
        run: docker build -t shubhamdockr/paynow:latest .

  Pushing_Docker_Image:
    runs-on: ubuntu-latest
    needs: Building_Docker_Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pushing Image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u shubhamdockr --password-stdin
          docker push shubhamdockr/paynow:latest
      
